### ISSUE TITLE
Marionette 2.3.2

### ISSUE THREAD

**Issue by denisw** [chancancode/marionette-rails#29]
It would be nice if `marionette-rails` could be updated to the latest release in the new 2.3.x series ([changelog](https://github.com/marionettejs/backbone.marionette/blob/master/changelog.md#v232-view-commit-logs)).

**Comment by wingrunr21** [comment]
Released. Feel free to submit a PR for a version bump next time.

**Comment by denisw** [comment]
Thank you!
