### ISSUE TITLE
Marionette 2.4.1 released

### ISSUE THREAD

**Issue by denisw** [chancancode/marionette-rails#30]
A new version of Marionette ([2.4.1](https://github.com/marionettejs/backbone.marionette/blob/master/changelog.md#v241-view-commit-logs)) is available. It would be nice if the gem could be updated.

**Comment by wingrunr21** [comment]
It would be nice if you would send Pull Requests for this instead of a passive-aggressive issue.

**Comment by wingrunr21** [comment]
Released

**Comment by denisw** [comment]
I didn't want to come across as passive-aggressive - sorry If I did. You are right that I should have sent a pull request, though. I will do so next time.

**Comment by wingrunr21** [comment]
:+1:
