### ISSUE TITLE
Add support for Marionette 1.8.8 as the last version in 1.x branch.

### ISSUE THREAD

**Issue by mareksuscak** [chancancode/marionette-rails#32]
Hello, would it be possible to make one more release of this gem that would feature Marionette 1.8.8 as the last supported version in the 1.x branch? We still depend upon it and won't be migrating anytime soon so we thought it might be a good idea to at least move to the latest stable minor and patch version. If no, are you accepting pull requests? I could put it together myself. Would you be willing to at least accept a PR and make a release of the gem? Thanks. 

UPDATE: Hmm there's no branch which I could create a PR against. I'd suggest creating `v1.x` - I've updated Marionette in my fork already - https://github.com/mareksuscak/marionette-rails/tree/v1.x

Buy I can't create a PR until there's a dedicated branch in your repo.

**Comment by wingrunr21** [comment]
I'll pull in 1.8.8 and release it today

**Comment by mareksuscak** [comment]
@wingrunr21 Thank you! I appreciate it.

**Comment by wingrunr21** [comment]
Released
